name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.70"

      - name: Build
        run: hugo -s . --config ./config.toml --buildDrafts --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: remoteworklibrary/remoteworklibrary.github.io
          publish_dir: ./public
          #keep_files: true
          user_name: adersberger
          user_email: josef.adersberger@qaware.de
          publish_branch: master
          cname: www.remoteworklibrary.io
