name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo -s . --config ./config.toml --buildDrafts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: adersberger/adersberger.github.io
          publish_dir: ./public
        #   keep_files: true
          user_name: adersberger
          user_email: josef.adersberger@qaware.de
          publish_branch: master
        #   cname: example.com
