name: CI

on: push

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: europe-west4
  SERVICE_NAME: remoteworklibrary

jobs:
  deploy-prod:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.2"

      - name: Build
        run: hugo -s . --config ./config.toml --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: remoteworklibrary/remoteworklibrary.github.io
          publish_dir: ./public
          #keep_files: true
          user_name: adersberger
          user_email: josef.adersberger@qaware.de
          publish_branch: master
          cname: www.remoteworklibrary.io

      # Setup gcloud CLI
      - name: setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Configure docker to use the gcloud command-line tool as a credential helper  
      - run: gcloud auth configure-docker
      
      # Build the Docker image
      - name: Build
        run: docker build . --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
        
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
        
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: gcloud components install beta && gcloud beta run deploy $SERVICE_NAME --quiet --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA --project $PROJECT_ID --region $RUN_REGION --platform managed --allow-unauthenticated

      # Deploy image to Cloud Run
      #- name: gcloud deploy
      #  run: |-
      #    gcloud run deploy "$SERVICE_NAME" \
      #    --quiet \
      #    --region "$RUN_REGION" \
      #    --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
      #    --platform "managed" \
      #    --allow-unauthenticated
